name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:latest

  update-manifests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout manifests repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.actor }}/hello-manifests
        token: ${{ secrets.GH_PAT }}
        path: manifests

     - name: Update image tag in deployment.yaml
      run: |
        cd manifests
        sed -i 's|nicolascasser/hello-app:.*|${{ secrets.DOCKER_USERNAME }}/hello-app:latest|g' deployment.yaml

    - name: Commit and push changes
      run: |
        cd manifests
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "CI: Update image to latest"
        git push